version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./vectorstore:/app/vectorstore
    environment:
      - PYTHONPATH=/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    
  gui:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - PYTHONPATH=/app
    command: streamlit run gui/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
